CREATE TABLE IF NOT EXISTS `party` (
  `party_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(24) NOT NULL DEFAULT '',
  `exp` TINYINT(11) UNSIGNED NOT NULL DEFAULT '0',
  `item` TINYINT(11) UNSIGNED NOT NULL DEFAULT '0',
  `leader_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `leader_char` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`party_id`)
) ENGINE=InnoDB;

