#!/bin/sh

dir=`pwd`

export LANG=C

make clean

#export CFLAGS="-std=c99 -Wvariadic-macros -Wvla -Wredundant-decls

export CFLAGS="-std=gnu99 -Wvariadic-macros -Wvla -Wredundant-decls \
-Wpacked-bitfield-compat -Wtrampolines \
-Wsuggest-attribute=noreturn -Wstrict-aliasing=2 \
-fstrict-aliasing -Wunreachable-code -Wabi -Wdisabled-optimization \
-Wvolatile-register-var -Winvalid-pch -Wredundant-decls \
-Wnormalized=nfkc -Wmissing-format-attribute -Wmissing-noreturn \
-Wswitch-default -Waddress \
-Wlogical-op -Wcast-align -Wpointer-arith -Wundef \
-Wmissing-include-dirs -Winit-self -pedantic -Wall -ggdb3 -O2 -pipe \
-Wpacked -Wstrict-overflow=1 -Wunknown-pragmas -Wwrite-strings \
-Wstack-protector -Wshadow -Wunused-macros \
-Wbuiltin-macro-redefined -Wdeprecated \
-Wendif-labels -Wformat=1 -Wimport -Wpsabi \
-Wmissing-field-initializers -Wuninitialized \
-Wignored-qualifiers -Winit-self -Wempty-body -Wclobbered -Wtype-limits \
-Wsign-compare -Wwrite-strings"

make 2>make.log
